theme: jekyll-theme-cayman

title: "Curso de Actualización en Métodos y Técnicas de Investigación"
description: "Materiales y guías para el curso de estadística y métodos de investigación"

# Esto es clave para que funcione en la subcarpeta
baseurl: "/curso-investigacion"
url: "https://cristhianjaramillo.com"
include:
  - assets/css/custom.css
